apiVersion: v1
kind: ConfigMap
metadata:
  name: connect-log4j-config
data:
  connect-log4j.properties: |-
        {{- .Files.Get "config/connect-log4j.properties" | nindent 5 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: connect-distributed-config
data:
  connect-distributed.properties: |-
        {{- .Files.Get "config/connect-distributed.properties" | nindent 5 }}
